# Generated by Django 2.2.2 on 2020-03-21 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_image_hits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='hits',
            new_name='page',
        ),
    ]
