# Generated by Django 2.2.2 on 2020-03-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20200321_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='page',
        ),
    ]
